### ISSUE TITLE
AppDaemaon 0.7.0 (Home Assistant add-on) doesn't start an old iPad2

### ISSUE THREAD

**Issue by kovaccs** [hassio-addons/app-appdaemon#146]
I have an old iPad2 dashboard on my house wall. As a Home Asistant user the only possibility to use on this tablet the AppDaemon screen for control HA because of - I think - the old IOS authorisation schema. I use it with satisfaction, but after the last AppDaemon upgrade the screen doesn't appear correctly. I had to restore the latest version (0.6.2).
Host: RPI4, Home Assistant OS 6.2; HA Core: 2012.8.7
This will be a final state or some solution is possible so that iOS 9.3.5 can also display AppDaemon4?  
Thank's: Kovaccsaba

**Comment by frenck** [comment]
Please describe the issue you are experiencing, because that is left out of the story...

**Comment by kovaccs** [comment]
> Please describe the issue you are experiencing, because that is left out of the story...

Yes, It's true!  :-)
After start displaying the configured dashboard the backgroud picture ok, but the objects locations are appear with a grayed form. Nothing else (icons and text, ....) displayed. (Sorry but I haven't take picture, before I had restore the snapshot.) 
Kovaccsaba

**Comment by kovaccs** [comment]
... one's more: This anomaly is only on iPad, on the PC browsers everithing ok!
Kovaccsaba

**Comment by frenck** [comment]
Aah, that is the same old issue they ran into more often in the past and they keep breaking it from time to time, instead of fixing it correctly.

The problem is that their Socket.io backend implementation in Python vs one used in their frontend, has a protocol version mismatch, causing it not to work.

Here is some history:

- https://github.com/hassio-addons/addon-appdaemon/issues/64
- https://github.com/AppDaemon/appdaemon/issues/1140

Please report this issue with the AppDaemon project itself.

<https://github.com/AppDaemon/appdaemon/issues>

**Comment by kovaccs** [comment]
Thank U Franck for this rapid anwers. I'll report it as You suggested. Thank you!

**Comment by frenck** [comment]
There is a issue open already:

<https://github.com/AppDaemon/appdaemon/issues/1335>

I've responded with more details there now as well.

**Comment by kovaccs** [comment]
> There is a issue open already:
> 
> [AppDaemon/appdaemon#1335](https://github.com/AppDaemon/appdaemon/issues/1335)
> 
> I've responded with more details there now as well.
Oh!  That's good, I can see!

**Comment by jduckles** [comment]
I'm seeing this same problem on an older iPad 3rd generation as well. Is there an easy way to roll App Daemon back to the older version while waiting for the fix?

Edit: Got a roll back to work from my snapshots.
