### ISSUE TITLE
(custom) Apps disappeared by upgrading to 0.15

### ISSUE THREAD

**Issue by adaenzer** [hassio-addons/app-appdaemon#302]
# Problem/Motivation

> the appdaemon apps were flushed without creating a backup (the backup file does not contain the app python files)
 for further context: i was working on a custom app of which i haven't made backups so far. the work i've done since the last ha-core update (which one's backup contains the files) seems to be lost.

## Expected behavior

> move the files instead of deleting them without prior notice, clear and obvious warning before the update that data will get lost and include the files to be altered, moved, deleted in the backup

## Actual behavior

> files of custom app can't be found anymore

## Steps to reproduce

> i guess many ran or will run into the same issue

## Proposed changes

> see expected behavior

@frenck , don't get me wrong, you've done great work and i don't even question reasons why you move files around. however, it is quite nervewrecking to find out that the config is broken and apparently the work of the last few days seems lost. i would have expected the backup to at least include the files that are deleted, so i could restore them.

**Comment by adaenzer** [comment]
and by the way: moving the files out of the home assistant config makes them unaccessible for the studio code server, which is quite inconvenient. is there a workaround?

**Comment by BarryS83** [comment]
> and by the way: moving the files out of the home assistant config makes them unaccessible for the studio code server, which is quite inconvenient. is there a workaround?

Yes there is a workaround. Leave, or move, the apps and the apps.yaml at to their original/old location.

Than in de appdaemon.yaml add the following on the new AppDaemon location add the below to the "addon_configs/a0d7b954_appdaemon/appdaemon.yaml":

appdaemon:
  app_dir: /homeassistant/appdaemon/apps

This works. Now you can still edit from HomeAssistant your apps, HACS still installs and updates apps on that location as well. So that will remain functional as well.

Edit: fixed typo

**Comment by Adya84** [comment]
I've installed from new wor
ked for a day now all vanished and no idea how to fix it

**Comment by Biotronic** [comment]
I too am having this problem, and there is no folder at /addon_configs/a0d7b954_appdaemon (/addon_configs/a0d7b954_nodered exists, so I'm pretty sure I have the right addon_configs folder). My immediate response to 0.15 not working was to revert to 0.14 - did this delete the folder?

[edit] Found a relatively new Core backup, which contained the appdaemon folder and my scripts, so I'm not entirely out of luck. :)

**Comment by DJBenson** [comment]
> > and by the way: moving the files out of the home assistant config makes them unaccessible for the studio code server, which is quite inconvenient. is there a workaround?
> 
> Yes there is a workaround. Leave, or move, the apps and the apps.yaml at to their original/old location.
> 
> Than in de appdaemon.yaml add the following on the new AppDaemon location add the below to the "addons_configs/a0d7b954_appdaemon/appdaemon.yaml":
> 
> appdaemon: app_dir: /homeassistant/appdaemon/apps
> 
> This works. Now you can still edit from HomeAssistant your apps, HACS still installs and updates apps on that location as well. So that will remain functional as well.

Do you have any idea whose responsibility it would be to address the fact that HACS can't access the new addons_config folder? I use an appdaemon app (https://github.com/springfall2008/batpred) which can't be updated by HACS if it's moved to the new location so the workaround is as you posted but I'm trying to work out with the developer whether it's the HACS developers or the AppDaemon developers who need to address making it work with the new directory structure.

**Comment by amaisano** [comment]
> Than in de appdaemon.yaml add the following on the new AppDaemon location add the below to the "addons_configs/a0d7b954_appdaemon/appdaemon.yaml":

TYPO! It's `addon_configs/` NOT `addons_configs/`

**Comment by adaenzer** [comment]
thanks @BarryS83 , i did what you suggested, but also added a symlink 
`ln -s /root/addon_configs/a0d7b954_appdaemon /homeassistant/appdaemon_addonconfig`
so i have the files available to edit in studio code server, especially appdaemon.yaml
not sure how it will evolve in the future, but for the moment i guess it's the most flexible workaround.

**Comment by adaenzer** [comment]
> I too am having this problem, and there is no folder at /addon_configs/a0d7b954_appdaemon (/addon_configs/a0d7b954_nodered exists, so I'm pretty sure I have the right addon_configs folder). My immediate response to 0.15 not working was to revert to 0.14 - did this delete the folder?
> 
> [edit] Found a relatively new Core backup, which contained the appdaemon folder and my scripts, so I'm not entirely out of luck. :)

the update to 0.15 deleted (not moved) the files and since they weren't included in the backup, reverting did not bring them back... the same core update also saved me from major losses! i have to debug what adjustments i made in the last week so it all worked as it finally did, but at least it's not a total loss.

**Comment by dMopp** [comment]
The current version needs to be pulled ... now all my apps are gone. WTF

i ahve to restore my whole vm backup, start it, recover the files by hand and pray.. wtf

**Comment by meazzle2111** [comment]
WHY THE HELL WOULD YOU MOVE FILES??????? I lost files that i worked on for days. Come on Man

**Comment by six50joe** [comment]
I thank and will continue to thank all the contributors to Home Assistant and its integrations and enhancements for the benefit of the user community.  Having said that, during my experience with HA it has been surprising to say the least.  It's almost a shock how often an incremental update breaks things for so many users because configuration metadata has changed or bugs are introduced.  And in some cases, like this one, not only is there a lack of documentation to guide the user as to what they need to do post upgrade just to keep the functionality they already have, but configuration and implementation is destroyed as a direct result of the update.  I always make backups of HA and my own implementation prior to every update so I was able to recover, but I should not have to, nor should anyone else.

Basic use case testing- never mind regression testing and useful information often seem to be an afterthought at best in the HA world.   We shouldn't have to be afraid to update our software regularly for bug fixes, efficiency and quality of life improvements, given the size of the user community impacted.   I am because I've been burnt too many times on this platform. 

I plead to all HA contributors **not** to publish updates without better quality assurance practices- and just as important, documentation that is comprehensive- not esoteric.  Too often many of us get drawn into the promise of value added features only to spend an hour, an afternoon, maybe days more than we thought we would trying to get something to work.   Time we won't get back.  

I'd bet an overwhelming majority in the HA community would be happy waiting longer for updates knowing they are more thoroughly prepared.

I am sort of ranting here but also pleading- and thanks again for all your contributions!

**Comment by quazar22** [comment]
I am seriously hoping that this is a lesson learned for you guys. I have lost DAYS of work due to this most recent change. I admit it is partially my fault for not performing full backups more often, but you absolutely screwed up here. Please, PLEASE be much more careful with your updates in the future. I am now going to look at any future appdaemon update with much more skepticism, as your reputation has been very tarnished for me by this update.

**Comment by frenck** [comment]
>  but you absolutely screwed up here

Sorry have to disagree.

> lease, PLEASE be much more careful with your updates in the future.

I made an error in the first release, corrected it within 2 hours, didn't occur in my testing. I've apologized for that and provided instructions for recovery.

../Frenck

**Comment by dMopp** [comment]
Hey, of cause we are all kind of frustrated, but at least for me not in you as a person. (Mainly due to unexpected work, like you had, too)

anyway a last question: Is the new folder part of a backup and yes which one? ha itself or addon?

**Comment by frenck** [comment]
> Is the new folder part of a backup and yes which one? ha itself or addon?

It is part of the add-on backup now (which is the whole reason to do this migration to the new structure in the first place).
