### ISSUE TITLE
Breaking changes not showing in addon update changelog in HA

### ISSUE THREAD

**Issue by Xitee1** [hassio-addons/app-appdaemon#303]
# Problem/Motivation

For some reason not all information of the changelog is shown in the HA addon update screen.

After updating AppDaemon to 0.15.2 it no longer started. After googling a while I found #287 and after fixing it I've noticed that actually the breaking change is mentioned in the changelog.
But since I only read it directly in HA, it wasn't displayed there and I assumed this was just some small update without anything breaking.
I don't know exactly if this is a HA problem or an issue with this specific Addon. But it should get fixed so we no longer miss important details.

![chrome_aYSxcCJtYl](https://github.com/hassio-addons/addon-appdaemon/assets/59659167/eb8e6fd1-cd8a-40a1-9ad3-cfd544ef0e96)
![chrome_AVg93lNfZQ](https://github.com/hassio-addons/addon-appdaemon/assets/59659167/a8a7c319-d133-4bc8-ab65-98d2cb2b46bf)

## Expected behavior

Showing all information of the changelog

## Actual behavior

Some very important details are missing

## Steps to reproduce

Have e.g. AD 0.15.1 installed whilst showing an update to version 0.15.2

## Proposed changes

Workaround:
Always do some extra steps and go to Github to check the changelogs.

**Comment by MrApplejuice** [comment]
May I add to this?... I just spent 1-2 hours debugging this issue. Thanks for creating this one to put me on the right track. But there is an annoying follow-up error resulting from the secrets thing. After the update, the files get moved around, all fine and good - mostly. Mine got moved with the `secrets: /config/secrets.yaml` still in place, which causes this error:

~~~~~~~~~~~~~~~~
[19:51:04] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
ERROR Error loading secrets file: /config/secrets.yaml
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
~~~~~~~~~~~~~~~~
(I accidentally truncated this log... sorry... it exits with `None type not iterable`)

Thanks to this issue, I was able to fix the issue by logging in on the backend and issueing:

![image](https://github.com/hassio-addons/addon-appdaemon/assets/542105/33436429-3d80-4cc7-a9c7-dee1c8d613cd)

To edit the line in question. This fixed the issue. However, I would propose a graceful recovery in case the secrets-file cannot be loaded, especially because the config files were moved and it is unclear how to edit them. Maybe just leave it at an error and continue, not allowing secrets to be interpreted?

Anyway, thanks for the work from my side! I can only imagine how hard it is to maintain a popular plugin with so many moving parts...

**Comment by MrApplejuice** [comment]
I feel the need to clarify: It would also be great if the update tries to move the files _again_ if it finds them still present in the `/config/` folder and overwrite them in the target location. That offers an easy route for people to recover from the issue should they be hit without figuring out the path above...

**Comment by jokerigno** [comment]
same here 
![immagine](https://github.com/hassio-addons/addon-appdaemon/assets/23552762/9998c97b-478c-44b6-b47f-7618974afcab)

**Comment by frenck** [comment]
This isn't incorrect, it shows the latest change.

The missing part highlighted was later added to the release notes, that doesn't change what is already shipped out.

../Frenck
