### ISSUE TITLE
HAASIO 2024.04 AppDaemon fails to start after initial installation

### ISSUE THREAD

**Issue by leprechaun17** [hassio-addons/app-appdaemon#337]
# Problem/Motivation

AppDaemon app fails to start after initial installation

## Expected behavior

To actually start

## Actual behavior

Error associated with secrets.yaml file not found. Not Appdaemon folder or yaml files are created to modify.

## Steps to reproduce

See log info:
s6-rc: info: service legacy-services: starting
[10:54:34] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
ERROR Error loading secrets file: /config/secrets.yaml
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by thouters** [comment]
I have the same issue, my config/appdaemon folder appears empty as well o_O

**Comment by tjorim** [comment]
Make sure you have a secrets.yaml in your add-on config directory. It's not the same as the home assistant config directory.

**Comment by thouters** [comment]
I hit the update button by accident this morning instead of start. I tried resetting to default settings using the addon UI. Now it seems my scripts and dashboard are gone in my hassio vscode instance. Will have to investigate tonight.

**Comment by thouters** [comment]
Regarding the issue I reported. So I hit the update button by accident, and no questions asked it upgraded me past https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.2 - which moves the configuration to a container specific share. My configuration was moved there. After changing the secrets path it worked again like before. I suspect people who have auto update on will have breakage because of things like that. Perhaps if the addon can move config, it can do a simple find and replace in the configfile too next time?
